insert into "JOB_TITLE" ("NAME") values ('CEO');
insert into "JOB_TITLE" ("NAME") values ('CTO');
insert into "JOB_TITLE" ("NAME") values ('COO');
insert into "JOB_TITLE" ("NAME") values ('IT Manager');
insert into "JOB_TITLE" ("NAME") values ('IT Specialist');
insert into "JOB_TITLE" ("NAME") values ('HR Manager');
insert into "JOB_TITLE" ("NAME") values ('HR Specialist');
insert into "JOB_TITLE" ("NAME") values ('Accountant');
insert into "JOB_TITLE" ("NAME") values ('Sales Manager');
insert into "JOB_TITLE" ("NAME") values ('Sales Specialist');
insert into "JOB_TITLE" ("NAME") values ('Sales Assistant');
