drop table if exists EMPLOYEE;

-- CREATETABLE
CREATE TABLE "EMPLOYEE" (
    "ID" SERIAL NOT NULL,
    "NAME" TEXT NOT NULL,
    "PHONE" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "BRANCH" TEXT NOT NULL,
    CONSTRAINT "EMPLOYEE_PKEY" PRIMARY KEY ("ID")
);